# Generated by Django 2.0.4 on 2018-04-18 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfield',
            name='content',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
